name: Update posts.json
on:
  workflow_dispatch:
  push:
    paths:
      - "posts.json"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Commit changes
        run: |
          git config --global user.name "kyontan-bot"
          git config --global user.email "actions@github.com"
          git add posts.json
          git commit -m "Update posts.json via Actions" || echo "No changes"
          git push

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
